<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PBR_Material_Maker</RootNamespace>
    <AssemblyName>PBR Material Maker</AssemblyName>
    <ApplicationIcon>PBR_Material_Maker.ico</ApplicationIcon>
    <Platforms>AnyCPU</Platforms>

    <!-- Hinzugefügte Eigenschaften -->
    <AssemblyTitle>PBR Material Maker</AssemblyTitle>
    <AssemblyDescription>A tool for creating, editing, and managing PBR materials for 3D graphics applications.</AssemblyDescription>
    <AssemblyCompany>PBR Material Maker</AssemblyCompany>
    <AssemblyProduct>PBR Material Maker</AssemblyProduct>
    <AssemblyVersion>3.8.604.0</AssemblyVersion>
    <FileVersion>3.8.604.0</FileVersion>
    <InformationalVersion>3.8.604</InformationalVersion>
    <TargetPlatform>Windows7.0</TargetPlatform>
    <SupportedOSPlatform>Windows7.0</SupportedOSPlatform>
  </PropertyGroup>

  <PropertyGroup>
    <EnableDefaultItems>true</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <!-- Ressourcen-Verzeichnis rekursiv einbinden -->
    <None Include="Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="PBR_Material_Maker.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="material_presets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="material_save.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- Kopiert alle Dateien aus Resources rekursiv ins Ausgabeverzeichnis -->
  <ItemGroup>
    <Content Include="Resources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
